Fix an issue with stream_for function call.
paysera/lib-rest-client-common pull request #12
Opened 2023-02-24 09:23 UTC by Laurgrin

2023-02-28 18:10 UTC, borilyordanov requested changes

2023-02-28 18:10 UTC, borilyordanov commented on composer.json
> +    "guzzlehttp/psr7": "^2.0"
It is better to be:
- conservative when dropping support for older versions of your dependencies;
- liberal when adding support for new versions of your dependencies.

In our case, we can keep the support for both versions by adjusting our code.

2023-02-28 18:10 UTC, borilyordanov commented on src/Client/ApiClient.php
> +            $request = $request->withBody(Utils::streamFor($content));
Let's adjust the code to support both versions of `guzzlehttp/psr7`.

We can check if the function `\GuzzleHttp\Psr7\stream_for()` exists (e.g. `function_exists('\GuzzleHttp\Psr7\stream_for')`) and then use it, otherwise use the new `\GuzzleHttp\Psr7\Utils\streamFor()` static method.

2023-02-28 18:10 UTC, borilyordanov commented on CHANGELOG.md
> +## 3.0.0
Why are we bumping the MAJOR version? In this case, we can bump just the PATCH version, because this is a backwards compatible bug fix.

2023-03-07 05:15 UTC, Laurgrin commented on src/Client/ApiClient.php
> +            $request = $request->withBody(Utils::streamFor($content));
We can, but should we? Older projects have no reason to upgrade this library, and new ones can use upgraded everything.

2023-03-07 05:15 UTC, Laurgrin commented on CHANGELOG.md
> +## 3.0.0
Why should we add a hack to just support something old? That's how we get the abysmal state of our libraries.

2023-03-07 05:15 UTC, Laurgrin commented on composer.json
> +    "guzzlehttp/psr7": "^2.0"
We can, but should we?

2023-03-07 05:15 UTC, Laurgrin commented on src/Client/ApiClient.php
> +            $request = $request->withBody(Utils::streamFor($content));
Or just upgrade like normal people.

2023-03-07 12:09 UTC, borilyordanov requested changes

2023-03-07 12:09 UTC, borilyordanov commented on src/Client/ApiClient.php
> +            if (method_exists(Utils::class, 'streamFor')) {
We can actually wrap the logic into a separate private method, e.g. `streamFor()`, which will serve as a proxy for choosing which method/function to use internally. This way our code will be easier to reason about. What do you think?

For example:
```php
$request = $request->withBody($this->streamFor($content));
```

2023-03-07 12:09 UTC, borilyordanov commented on CHANGELOG.md
> +- Bumped the version with a major as changes are not backwards compatible.
This line is not relevant anymore.

2023-03-07 12:09 UTC, borilyordanov commented on CHANGELOG.md
> +- Bumped `guzzlehttp/psr7` to `^2.0`
This line is not relevant anymore.

2023-03-07 12:09 UTC, borilyordanov commented on CHANGELOG.md
> +### Changed
Actually if we are fixing a bug where `stream_for()` function can be missing we might use `Fixed` section instead.

2023-03-07 12:09 UTC, borilyordanov commented on composer.json
> +    "guzzlehttp/psr7": "^2.0"
As I mentioned, it's generally better to refrain from releasing MAJOR versions frequently. Of course everything depends on the situation and the circumstances.

In our case it doesn't cost us a lot to support v1.x of `guzzlehttp/psr7`. If at some point in the future the burden of supporting some old dependency outweighs the benefit, we drop the support in favor of development of our package.

If at some point in the future the burden of maintaining some old dependency outweighs the benefit, we drop support in favor of our package development.

2023-03-09 09:54 UTC, borilyordanov approved these changes

2023-03-09 09:55 UTC, merged